"""add sys_setting table

Revision ID: 5f7084674727
Revises: 7968347e0d00
Create Date: 2026-05-18 13:41:55.635084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f7084674727'
down_revision = '7968347e0d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_setting',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=128), nullable=False),
    sa.Column('setting_group', sa.String(length=64), nullable=False),
    sa.Column('setting_type', sa.String(length=32), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    with op.batch_alter_table('cmdb_vm', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='虚拟机名称',
               existing_nullable=False)
        batch_op.alter_column('cluster',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='所属集群',
               existing_nullable=False)
        batch_op.alter_column('external_ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment=None,
               existing_comment='外部 IP 地址',
               existing_nullable=False)
        batch_op.alter_column('internal_ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment=None,
               existing_comment='内部 IP 地址',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='描述说明',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='状态（1=在线, 0=离线）',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('tenant',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='所属租户',
               existing_nullable=False)
        batch_op.alter_column('vcpus',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='CPU 核数',
               existing_nullable=False,
               existing_server_default=sa.text("'4'"))
        batch_op.alter_column('memory',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='内存（MB）',
               existing_nullable=False,
               existing_server_default=sa.text("'8192'"))
        batch_op.alter_column('disk',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='硬盘容量',
               existing_nullable=True)
        batch_op.alter_column('access_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='访问地址',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='创建人',
               existing_nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='更新人',
               existing_nullable=True)
        batch_op.alter_column('deleted',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='逻辑删除（0=未删, 1=已删）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('idx_cluster'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_tenant'))
        batch_op.drop_index(batch_op.f('uk_name_deleted'))
        batch_op.drop_table_comment(
        existing_comment='CMDB 虚拟机资产表'
    )

    with op.batch_alter_table('sys_common_link', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='链接名称',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment=None,
               existing_comment='描述',
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='跳转地址',
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='图标名称',
               existing_nullable=True)
        batch_op.alter_column('sort',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序号（升序）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('enabled',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='是否启用（1=是, 0=否）',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_table_comment(
        existing_comment='首页常用链接配置表'
    )

    with op.batch_alter_table('sys_monitor', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('server_online',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='在线服务器数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('service_running',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='运行中服务数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('network_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='网络状态（normal/abnormal）',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'"))
        batch_op.alter_column('storage_usage',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='存储使用率',
               existing_nullable=True)
        batch_op.alter_column('alert_pending',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='未处理告警数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('cpu_load',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='CPU 负载',
               existing_nullable=True)
        batch_op.alter_column('snapshot_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='快照时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_table_comment(
        existing_comment='系统状态快照表'
    )

    with op.batch_alter_table('sys_recent_visit', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='用户 ID',
               existing_nullable=False)
        batch_op.alter_column('page_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='页面路由路径',
               existing_nullable=False)
        batch_op.alter_column('page_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='页面标题',
               existing_nullable=False)
        batch_op.alter_column('visited_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='访问时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_user_visited'))
        batch_op.drop_table_comment(
        existing_comment='用户最近访问记录表'
    )

    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment=None,
               existing_comment='角色',
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('deleted',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment=None,
               existing_comment='逻辑删除',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('uk_username_deleted'))
        batch_op.drop_table_comment(
        existing_comment='系统用户表'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sys_user', schema=None) as batch_op:
        batch_op.create_table_comment(
        '系统用户表',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('uk_username_deleted'), ['username', 'deleted'], unique=True)
        batch_op.alter_column('deleted',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='逻辑删除',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='角色',
               existing_nullable=False,
               existing_server_default=sa.text("'user'"))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               comment='邮箱',
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               comment='密码哈希',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='用户名',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sys_recent_visit', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户最近访问记录表',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_user_visited'), ['user_id', 'visited_at'], unique=False)
        batch_op.alter_column('visited_at',
               existing_type=mysql.DATETIME(),
               comment='访问时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('page_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='页面标题',
               existing_nullable=False)
        batch_op.alter_column('page_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='页面路由路径',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(),
               comment='用户 ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sys_monitor', schema=None) as batch_op:
        batch_op.create_table_comment(
        '系统状态快照表',
        existing_comment=None
    )
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('snapshot_time',
               existing_type=mysql.DATETIME(),
               comment='快照时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('cpu_load',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='CPU 负载',
               existing_nullable=True)
        batch_op.alter_column('alert_pending',
               existing_type=mysql.INTEGER(),
               comment='未处理告警数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('storage_usage',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='存储使用率',
               existing_nullable=True)
        batch_op.alter_column('network_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='网络状态（normal/abnormal）',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'"))
        batch_op.alter_column('service_running',
               existing_type=mysql.INTEGER(),
               comment='运行中服务数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('server_online',
               existing_type=mysql.INTEGER(),
               comment='在线服务器数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sys_common_link', schema=None) as batch_op:
        batch_op.create_table_comment(
        '首页常用链接配置表',
        existing_comment=None
    )
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('enabled',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='是否启用（1=是, 0=否）',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('sort',
               existing_type=mysql.INTEGER(),
               comment='排序号（升序）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='图标名称',
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='跳转地址',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               comment='描述',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='链接名称',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('cmdb_vm', schema=None) as batch_op:
        batch_op.create_table_comment(
        'CMDB 虚拟机资产表',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('uk_name_deleted'), ['name', 'deleted'], unique=True)
        batch_op.create_index(batch_op.f('idx_tenant'), ['tenant'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_cluster'), ['cluster'], unique=False)
        batch_op.alter_column('deleted',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='逻辑删除（0=未删, 1=已删）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('updated_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='更新人',
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='创建人',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('access_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='访问地址',
               existing_nullable=True)
        batch_op.alter_column('disk',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='硬盘容量',
               existing_nullable=True)
        batch_op.alter_column('memory',
               existing_type=mysql.INTEGER(),
               comment='内存（MB）',
               existing_nullable=False,
               existing_server_default=sa.text("'8192'"))
        batch_op.alter_column('vcpus',
               existing_type=mysql.INTEGER(),
               comment='CPU 核数',
               existing_nullable=False,
               existing_server_default=sa.text("'4'"))
        batch_op.alter_column('tenant',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='所属租户',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment='状态（1=在线, 0=离线）',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='描述说明',
               existing_nullable=True)
        batch_op.alter_column('internal_ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment='内部 IP 地址',
               existing_nullable=False)
        batch_op.alter_column('external_ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45),
               comment='外部 IP 地址',
               existing_nullable=False)
        batch_op.alter_column('cluster',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='所属集群',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='虚拟机名称',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('sys_setting')
    # ### end Alembic commands ###
